# Generated by Django 5.1.7 on 2025-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('home_garden', 'Home & Garden'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('books', 'Books'), ('music', 'Music'), ('gaming', 'Gaming'), ('stationary', 'Stationary'), ('other', 'Other')], max_length=100, unique=True, verbose_name='Category Name'),
        ),
    ]
