# Generated by Django 5.1.7 on 2025-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.CharField(blank=True, choices=[('home_garden', 'Home & Garden'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('books', 'Books'), ('music', 'Music'), ('gaming', 'Gaming'), ('stationary', 'Stationary'), ('other', 'Other')], null=True, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
