# Generated by Django 5.1.7 on 2025-03-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_subcategory_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shelf',
            new_name='category',
        ),
    ]
