# Generated by Django 5.1.7 on 2025-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_shelf_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Textile', 'Textile'), ('Organizers', 'Organizers'), ('Decor', 'Decor'), ('Lightning', 'Lightning'), ('Furniture', 'Furniture'), ('Bathroom', 'Bathroom'), ('Mobile Phones', 'Mobile Phones'), ('Other', 'Other')], verbose_name='Sub Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
