# Generated by Django 5.1.7 on 2025-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home & Garden', 'Home & Garden'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Music', 'Music'), ('Gaming', 'Gaming'), ('Stationary', 'Stationary'), ('Other', 'Other')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Kitchen', 'Kitchen'), ('Textile', 'Textile'), ('Organizers', 'Organizers'), ('Decor', 'Decor'), ('Lighting', 'Lighting'), ('Furniture', 'Furniture'), ('Bathroom', 'Bathroom'), ('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Accessories', 'Fashion Accessories'), ('Jewelry', 'Jewelry'), ('Mobile Phones', 'Mobile Phones'), ('Laptops', 'Laptops'), ('Headphones', 'Headphones'), ('Cameras', 'Cameras'), ('TVs', 'TVs'), ('Instruments', 'Instruments'), ('Vinyl', 'Vinyl'), ('CDs', 'CDs'), ('Headphones', 'Headphones'), ('Consoles', 'Consoles'), ('PC Games', 'PC Games'), ('Gaming Accessories', 'Gaming Accessories'), ('Virtual Reality', 'Virtual Reality'), ('Pens & Pencils', 'Pens & Pencils'), ('Notebooks', 'Notebooks'), ('Art Supplies', 'Art Supplies'), ('Other', 'Other')], null=True, verbose_name='Subcategory'),
        ),
    ]
